apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: spring-smoketest
spec:
  contact:
    team: jaime
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "21"
    path: ../..
  ports:
  - name: main
    port: 8080
